name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Create /tmp/commands.txt file
      run: |
        echo "# One-time command - Run at 11:00 on 14 May 2025" > /tmp/commands.txt
        echo "0 11 14 5 2025 echo \$(date) && echo \"At Amex we do whats right\"" >> /tmp/commands.txt
        echo "# Recurring every 1 minute" >> /tmp/commands.txt
        echo "*/1 echo \$(date) && echo \"Amex motto is Don't live life without it\"" >> /tmp/commands.txt

    - name: Run Scheduler for 1 minute
      run: |
        java -cp target/amex-schedule-0.1.jar com.amex.scheduler.AmexScheduler & sleep 65 && kill $!

    - name: Upload sample-output.txt
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sample-output
        path: sample-output.txt
